- app/src/main/java/gov/wa/wsdot/android/wsdot/di/FragmentBuildersModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/about/AboutFragment.kt
- app/src/main/res/layout/about_fragment.xml
- app/src/main/res/layout/amtrak_cascades_fragment.xml
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/navigation/nav_graph.xml
- app/src/main/res/values/strings.xml
> Adds about section

- app/src/main/java/gov/wa/wsdot/android/wsdot/WsdotApp.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/AppModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/FragmentBuildersModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/ViewModelModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/model/MapLocationItem.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/MapCamerasViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/MapLocationViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/gotolocation/GoToLocationBottomSheetFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/travelerinformation/TravelerInfoBottomSheetFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/travelerinformation/TravelerInfoMenuEventListener.kt
- app/src/main/res/navigation/nav_graph.xml
> Bottom Sheet Menu Fixes

- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/api/WebDataService.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/api/response/traffic/ExpressLanesStatusResponse.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/FragmentBuildersModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/ViewModelModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/repository/ExpressLanesRepository.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/binding/TrafficBindingAdapters.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/expresslanes/ExpressLanesFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/expresslanes/ExpressLanesListAdapter.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/expresslanes/ExpressLanesViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/menus/travelerinformation/TravelerInfoBottomSheetFragment.kt
- app/src/main/res/layout/express_lane_item.xml
- app/src/main/res/layout/express_lanes_fragment.xml
- app/src/main/res/menu/menu_express_lanes.xml
- app/src/main/res/navigation/nav_graph.xml
- app/src/main/res/values/strings.xml
- build.gradle
> Native express lanes

- app/src/main/java/gov/wa/wsdot/android/wsdot/db/traffic/CameraDao.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/FragmentBuildersModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/ViewModelModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/repository/CameraRepository.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/bordercrossings/BorderCrossingViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/bordercrossings/bordercameras/BorderCameraListFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/bordercrossings/bordercameras/BorderCameraListViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/bordercrossings/crossingtimes/BaseCrossingTimesFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/bordercrossings/crossingtimes/BorderCrossingTimesListAdapter.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/cameras/CameraListViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/favorites/FavoritesFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/favorites/recyclerview/FavoritesListAdapter.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/route/terminalCameras/TerminalCamerasViewModel.kt
- app/src/main/res/layout/border_crossing_item.xml
- app/src/main/res/navigation/nav_graph.xml
> Adds cameras to border waits

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/gov/wa/wsdot/android/wsdot/thirdparty/README.md
- app/src/main/java/gov/wa/wsdot/android/wsdot/thirdparty/glide/MyAppGlideModule.java
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/binding/BindingAdapters.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/binding/TrafficBindingAdapters.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/travelcharts/TravelChartBindingAdapters.kt
- build.gradle
> Removes Picasso in favor for Glide

- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/res/layout/camera_bottom_sheet.xml
- app/src/main/res/layout/highway_alert_bottom_sheet.xml
> fixes traffic map bottom sheet layout bug

- app/src/main/java/gov/wa/wsdot/android/wsdot/db/ferries/FerrySailingWithStatus.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/db/ferries/FerrySailingWithStatusDao.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/binding/FerriesBindingAdapters.kt
- app/src/main/res/layout/ferry_sailing_item.xml
Includes the name with the at dock status.
> Adds vessel name to sailing items

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/vesselwatch/VesselWatchFragment.kt
- app/src/main/res/layout/map_fragment.xml
- app/src/main/res/layout/vessel_watch.xml
adds call to set state as hidden on init
> fixes vessel watch bottom sheet

- .idea/jarRepositories.xml
- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/cameras/CameraFragment.kt
- app/src/main/res/layout/camera_fragment.xml
- app/src/main/res/layout/camera_item.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Using text only camera display no longer had space for image
> Fixes camera item spacing in fav

- app/src/main/java/gov/wa/wsdot/android/wsdot/db/traffic/HighwayAlertDao.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/di/ViewModelModule.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/repository/HighwayAlertRepository.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/trafficalerts/HighestAlertsFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/trafficalerts/HighwayAlertTabFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/trafficalerts/StatewideAndHighestImpactAlertsViewModel.kt
- app/src/main/res/layout/highway_alerts_highest_impact_fragment.xml
Issue #102 
Changes the highest impact alerts list to "Statewide **and** highest impact alerts list. This ensures no alerts are hidden by the filter that hides alerts with (0,0) location.
> Adds alerts with no location (0,0) to the statewide alerts list

- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/highwayAlerts/HighwayAlertFragment.kt
> Sets Highway Alert Details Map view to statewide view of Washington if alerts location is (0,0)

- app/src/main/java/gov/wa/wsdot/android/wsdot/WsdotApp.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/binding/BindingAdapters.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/route/ferryAlerts/FerryAlertDetailsFragment.kt
- app/src/main/res/values/apikeys.xml
When no data is available shows an error message instead of staying blank
Issue #106
> fixes empty ferry bulletin screen

- app/src/main/java/gov/wa/wsdot/android/wsdot/WsdotApp.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/service/MyFirebaseMessagingService.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/service/helpers/MyNotificationManager.kt
cleans up notification channel creation.
Issue #115
> Adds bridge alert channel

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/route/FerriesRouteFragment.kt
Disables calendar view and adds alert dialog directing users to the website.
Issue #137
> Add ferry schedule calendar alert message

- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/viewmodel/SharedDateViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/route/ferryAlerts/FerryAlertsFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/vesselwatch/VesselWatchFragment.kt
- app/src/main/res/layout/ferry_alert_item.xml
- app/src/main/res/layout/highway_alert_bottom_sheet.xml
- app/src/main/res/layout/rest_area_fragment.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Issue #144
- Issue #143
- Issue #142
- Issue #141
- Issue #140
- Issue #139
- MacOS Monterey Version 12.3.1
- Android Studio Bumblebee | 2021.1.1 Patch 2
> Maintenance & Bug Fixes

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
- Assigns emergency alerts to unique themeID
- Adds additional themes to match iOS app themes
New Theme List:
- ThemeWSDOTGreen = 0
- ThemeWSDOTOrange = 1
- ThemeWSDOTBlue = 2
- ThemeWSDOTCustom = 3
- ThemeWSDOTEmergency = 4
Issue #149
---------------------------
Development Environment 
---------------------------
- MacOS Monterey Version 12.4
- Android Studio Chipmunk | 2021.2.1 Patch 1
> Assign unique themeId for Emergency Alerts

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/eventbanner/EventBannerViewModel.kt
Issue #166
------------------
- macOS Monterey Version 12.6
- Android Studio Chipmunk | 2021.2.1 Patch 1
> Check for new emergency alert while app is open

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/DayPickerFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/route/FerriesRouteFragment.kt
- Restores ferry schedule calendar.
- Adds ferry calendar info button w/ message. 
------------------------
- Mac OS Ventura: 13.3.1 
- Android Studio Electric Eel | 2022.1.1 Patch 2
> Ferry Schedule Calendar

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/amtrakcascades/AmtrakCascadesFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/DayPickerFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/route/FerriesRouteFragment.kt
> Remove 'INFO' button from Amtrak Cascades calendar

- .gitignore
- .idea/gradle.xml
- .idea/kotlinc.xml
- .idea/misc.xml
- README.md
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/mountainpasses/report/MountainPassReportFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/travelerinformation/TravelerInfoBottomSheetFragment.kt
- Removed Twitter feed from the app.
- Updated configuration & README files.
- Mountain pass bug fixes.
> Remove Twitter Feed

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/notifications/NotificationsFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/notifications/recyclerview/TopicListAdapter.kt
- build.gradle
• Added permission dialog to notification page.
• Declares ad ID permissions in manifest.
• Dependency updates.
> Android 13 Update

- app/schemas/gov.wa.wsdot.android.wsdot.db.WsdotDB/4.json
- app/src/main/java/gov/wa/wsdot/android/wsdot/api/response/traffic/HighwayAlertsResponse.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/db/WsdotDB.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/db/traffic/HighwayAlert.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/repository/HighwayAlertRepository.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/service/MyFirebaseMessagingService.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/binding/BindingAdapters.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/ferries/FerriesHomeFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/highwayAlerts/HighwayAlertFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/notifications/NotificationsViewModel.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/notifications/recyclerview/TopicListAdapter.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/trafficalerts/HighestAlertsFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/trafficalerts/MapHighwayAlertsFragment.kt
- app/src/main/res/layout/about_fragment.xml
- app/src/main/res/layout/highway_alert_bottom_sheet.xml
- app/src/main/res/layout/highway_alert_fragment.xml
- app/src/main/res/layout/highway_alert_item.xml
- app/src/main/res/values/strings.xml
- Use priority id for alert icons.
- Use new category system for highway alerts.
- Add roadway location to highway alerts.
- Bug fixes & layout improvements.
--------------------------
- Mac OS Sonoma:  14.1
- Android Studio Giraffe | 2022.3.1 Patch 2
> Traveler Information Service API v2

- .idea/compiler.xml
- .idea/gradle.xml
- .idea/kotlinc.xml
- .idea/migrations.xml
- .idea/misc.xml
- app/schemas/gov.wa.wsdot.android.wsdot.db.WsdotDB/5.json
- app/src/main/java/gov/wa/wsdot/android/wsdot/api/response/traffic/HighwayAlertsResponse.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/db/WsdotDB.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/db/traffic/HighwayAlert.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/db/traffic/HighwayAlertDao.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/repository/HighwayAlertRepository.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/cameras/CameraFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/highwayAlerts/HighwayAlertFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/highwayAlerts/HighwayAlertListAdapter.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/restareas/RestAreaFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/travelerinformation/bridgeAlerts/BridgeAlertFragment.kt
- Adds alert midpoint location data.
- Fixes issues with statewide alerts.
-----------------------
- Mac OS Sonoma:  14.4.1
- Android Studio Iguana | 2023.2.1 Patch 1
> Midpoint data and statewide alerts

- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/repository/TollRateRepository.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- Dependency updates.
- Decrease static tolls data cache time.
-----------------------
- Mac OS Sonoma:  14.6.1
- Android Studio Koala | 2024.1.1
> Maintenance Updates

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/common/WebViewFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/traveltimes/TravelTimeFragment.kt
- app/src/main/res/layout/travel_time_item.xml
Fixes issue with travel time cluster items causing load time issues for the traffic map.
> Move cluster click logic out of travel times loop

- .idea/compiler.xml
- .idea/kotlinc.xml
- .idea/misc.xml
- README.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/gov/wa/wsdot/android/wsdot/api/WebDataService.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/notifications/recyclerview/TopicListAdapter.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/settings/FavoritesSortSettingFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/settings/SettingsFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/travelerinformation/TravelerInfoBottomSheetFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/travelerinformation/bridgeAlerts/BridgeAlertsFragment.kt
- app/src/main/res/values/themes.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- Updated Target SDK to 35
- Updated Gradle Plugin 8.8.0
- Fixed edge-to-edge formatting on Android 15
- Updated ferry schedules to use JSON file
-----------------------
- Mac OS Sequoia: 15.3.1
- Android Studio Ladybug Feature Drop | 2024.2.2
> Android 15 Update

- app/build.gradle
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/settings/FavoritesSortSettingFragment.kt
- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/trafficmap/TrafficMapFragment.kt
- Fixes a compilation issue for Intel-based Mac mini computers.
> Dependency Updates

- app/src/main/java/gov/wa/wsdot/android/wsdot/ui/MainActivity.kt
- Fix emergency alert banner formatting.
- Refresh alert banner when menu item selected.
-----------------------
- Mac OS Sequoia: 15.5
- Android Studio Narwhal | 2025.1.1 Patch 1
> Emergency Alert Improvements
